RootDir = ""
Addr = ":8071"
Compactor = "gzip"
Pipe = "http"
BatchDuration = 5
BatchLength = 100
Debug = false

[HttpPipe]
  Addr = "http://127.0.0.1:8070/collect"
  Auth = "midea"

[[Collects]]
  Name = "CPUCount"
  Duration = 5

[[Collects]]
  Name = "CPUInfo"
  Duration = 5

[[Collects]]
  Name = "CPUTimes"
  Duration = 5
