compactor = "gzip"
pipe = "http"
batch_duration = 5
batch_length = 100

[http_pipe_push]
  addr = "http://127.0.0.1:8070/collect"
  auth = "midea"

[[collects]]
  Name = "CPUCount"
  Duration = 5

[[collects]]
  Name = "CPUInfo"
  Duration = 5

[[collects]]
  Name = "CPUTimes"
  Duration = 5

[[collects]]
  Name = "Partitions"
  Duration = 5

[[collects]]
  Name = "BootTime"
  Duration = 5

[[collects]]
  Name = "KernelVersion"
  Duration = 5

[[collects]]
  Name = "PlatformInfo"
  Duration = 5

[[collects]]
  Name = "HostInfo"
  Duration = 5

[[collects]]
  Name = "Users"
  Duration = 5

[[collects]]
  Name = "Uptime"
  Duration = 5

[[collects]]
  Name = "Avg"
  Duration = 5

[[collects]]
  Name = "SwapMemory"
  Duration = 5

[[collects]]
  Name = "VirtualMemory"
  Duration = 5

[[collects]]
  Name = "Interfaces"
  Duration = 5