http_addr = ":8070"
mode = "persistence"

[http_pipe_pop]
  auth = "midea"
  pattern = "/collect"

[persistence]
  engine = "local"
  local_path = "/Users/zweite/Documents/go_proj/src/dudu/config/data/persistence.data"

[forward]
  pipe = "http"
  [forward.http_pipe_push]
    addr = "http://127.0.0.1:8070/collect"
    auth = "midea"
