[redis]

  [[redis.base]]
    host = "127.0.0.1"
    port = 6379

[etcd]

  [[etcd.base]]
    host = "127.0.0.1"
    port = 4010

  [[etcd.base]]
    host = "127.0.0.1"
    port = 4011

  [[etcd.base]]
    host = "127.0.0.1"
    port = 4012

[mongo]

  [[mongo.base]]
    host = "127.0.0.1"
    port = 27029
    db = "dudu"

[influx]
  host = "127.0.0.1"
  port = 8086
  db = "dudu"
